 
 CREATE TABLE IF NOT EXISTS tb_employee (
  id BIGSERIAL NOT NULL,
  name VARCHAR(60) NOT NULL,
  cpf VARCHAR(11) NOT NULL UNIQUE,
  CONSTRAINT tb_employee_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS tb_item(
  id BIGSERIAL NOT NULL,
  name VARCHAR(60) NOT NULL,
  employee_id BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (employee_id) REFERENCES tb_employee(id)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);
