CREATE TABLE IF NOT EXISTS tb_item(
  id BIGSERIAL NOT NULL,
  name VARCHAR(60) NOT NULL,
  employee_id BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (employee_id) REFERENCES tb_employee(id)
  ON UPDATE CASCADE
  ON DELETE CASCADE
);
